#!/bin/sh
### BEGIN INIT INFO
# Provides:          mos-resource-guardian
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MOS resource guard
### END INIT INFO
set -eu
case "${1:-}" in
  start|stop|status) exec /usr/bin/python3 /usr/lib/mos-resource-guardian/lifecycle.py "$1" ;;
  restart)
    /usr/bin/python3 /usr/lib/mos-resource-guardian/lifecycle.py stop
    exec /usr/bin/python3 /usr/lib/mos-resource-guardian/lifecycle.py start
    ;;
  *) echo 'Usage: start|stop|restart|status' >&2; exit 2 ;;
esac
